blank_issues_enabled: false
contact_links:
  - name: Have a formatting issue or feature request?
    url: https://github.com/marleyjs/logform/issues/new/choose
    about: Please search and report @ MarleyJS/Logform
  - name: Need help using Marley?
    url: https://stackoverflow.com/questions/tagged/marley
    about: Please look on StackOverflow first to see if someone has already answered your question.
